import type { Metadata } from "next";
import { Nunito, Poppins } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { cn } from "@/lib/utils";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

// * Fonts
const poppins = Poppins({
    subsets: ["latin", "latin-ext"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-sans",
});

const nunito = Nunito({
    subsets: ["latin", "latin-ext"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-heading",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={cn(
                    poppins.className,
                    nunito.variable,
                    "min-h-screen bg-background antialiased grainy"
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                ></ThemeProvider>

                <ReactQueryProvider>
                    <Navbar />
                    {children}
                </ReactQueryProvider>
            </body>
        </html>
    );
}
